name: "Render Template"
description: "Renders a template file using environment variables"

inputs:
  working-directory:
    description: "Directory where the template and values files are located"
    required: false
    default: ${{ github.workspace }}
  template:
    description: "Path to the template file"
    required: true
  values:
    description: "Path to shell script that exports values to be templated"
    required: true
  output:
    description: "Path where rendered template should be saved"
    required: true

runs:
  using: "composite"
  steps:
    - name: Source values and render template
      working-directory: ${{ inputs.working-directory }}
      shell: bash
      env:
        template: ${{ inputs.template }}
        values: ${{ inputs.values }}
        output: ${{ inputs.output }}
      run: |
        set -a
        source "$values"
        set +a
        envsubst < "$template" > "$output"
        env
