name: Get labels
description: "Returns the labels of the PR associated with github.sha"
runs:
  using: "composite"
  steps:
    - name: Output labels
      id: label
      shell: sh
      env:
        GH_TOKEN: ${{ github.token }}
        COMMIT_SHA: ${{ github.sha }}
      run: |
        NAMES=$(gh api graphql -f query='
          query($sha: String!) {
            search(query: $sha, type: ISSUE, first: 1) {
              edges {
                node {
                  ... on PullRequest {
                    number
                    title
                    labels(first: 10) {
                      nodes {
                        name
                      }
                    }
                  }
                }
              }
            }
          }
        ' -f sha="$COMMIT_SHA"  --jq '[.data.search.edges[0].node.labels.nodes[].name]')

        echo "names=$NAMES" >> "$GITHUB_OUTPUT"
outputs:
  names:
    description: "Labels of the PR associated with github.sha"
    value: ${{ steps.label.outputs.names }}
