name: Run markdown-link-check
description: Runs markdown-link-check in quiet mode and fails if there is any output.

runs:
  using: "composite"
  steps:
    - name: Markdown
      shell: sh
      run: npx markdown-link-check --quiet {staged_files} | (! grep .)
