name: MkDocs build strict
description: Runs mkdocs build with strict mode so any mistakes are caught early.
inputs:
  version:
    description: The version of mkdocs-material to install.
    required: false
    default: 9.6.11

runs:
  using: "composite"
  steps:
    - name: Cache pip packages
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: pip-mkdocs-material-${{ inputs.version }}-${{ runner.os }}
    - shell: sh
      env:
        version: ${{ inputs.version }}
      run: |
        pip install "mkdocs-material==$version"
        mkdocs build --strict
