name: Run ShellCheck
description: Runs ShellCheck with forced color and external sources

runs:
  using: "composite"
  steps:
    - name: Run ShellCheck
      shell: sh
      run: >
        git ls-files -z | xargs -0 file |
        ${GITHUB_ACTION_PATH}/filter.py |
        cut -d: -f1 | xargs
        shellcheck --color=always -x
    - if: always()
      shell: sh
      run: shellcheck --version
