name: Run ShellCheck
description: Runs ShellCheck with external sources

runs:
  using: "composite"
  steps:
    - name: Run ShellCheck
      shell: sh
      run: |
        shellcheck --version
        git ls-files -z | xargs -0 file | grep "script text executable" | cut -d: -f1 | xargs shellcheck -x
