name: Run ShellCheck
description: Runs ShellCheck with external sources

runs:
  using: "composite"
  steps:
    - name: Run ShellCheck
      run: >
        git ls-files -z | xargs -0 file |
        ./filter.py | cut -d: -f1 | xargs
        shellcheck -x
    - if: always()
      name: Print ShellCheck version
      run: shellcheck --version
