name: Run ShellCheck
description: Runs ShellCheck with forced color and external sources

runs:
  using: "composite"
  steps:
    - name: Run ShellCheck
      shell: sh
      run: |
        shellcheck --color=always -x $(git ls-files -z | ${GITHUB_ACTION_PATH}/filter.sh)
    - if: always()
      shell: sh
      run: shellcheck --version
