name: "Compare Lefthook glob"
description: "Compare changes to a Lefthook glob"
inputs:
  changes:
    description: "JSON array of changed files"
    required: true
  yq:
    description: "yq expression to extract glob pattern from the YAML file"
    required: true
  file:
    description: "YAML file to extract glob pattern from"
    required: false
    default: "lefthook.yml"
runs:
  using: "composite"
  steps:
    - name: Compare Lefthook glob
      id: state
      shell: sh
      env:
        changes: ${{ inputs.changes }}
        yq: ${{ inputs.yq }}
        file: ${{ inputs.file }}
        expression_path: ${{ runner.temp }}/expression
      run: |
        "$GITHUB_ACTION_PATH/action.py"
outputs:
  changed:
    description: "Boolean indicating whether any of the changed files match the glob pattern"
    value: ${{ steps.state.outputs.changed }}
