name: Editorconfig-Checker
description: Runs Editorconfig-Checker on files tracked by Git.

runs:
  using: "composite"
  steps:
    - name: Run Editorconfig-Checker
      shell: bash
      run: |
        mapfile -t FILES < <(git ls-files)
        npx editorconfig-checker "${FILES[@]}"
