name: Editorconfig-Checker
description: Runs Editorconfig-Checker on all files.

runs:
  using: "composite"
  steps:
    - name: Run Editorconfig-Checker
      shell: sh
      run: npx editorconfig-checker .
