name: check-relative-markdown-links
description: Installs and runs check-relative-markdown-links on default settings.
inputs:
  sha:
    required: false
    description: "SHA of the commit from which to install the tool"
    default: 6e0ca61a9e52799d4ee2e92b07e84074729d808d
  working-directory:
    required: false
    description: "Directory where the template and values files are located"
    default: ${{ github.workspace }}

runs:
  using: "composite"
  steps:
    - name: Cache
      uses: actions/cache@v4
      with:
        path: /usr/local/bin/check-relative-markdown-links
        key: check-relative-markdown-links-${{ inputs.sha }}
    - name: Install
      working-directory: ${{ inputs.working-directory }}
      shell: sh
      env:
        sha: ${{ inputs.sha }}
      run: |
        curl -sSfL "https://raw.githubusercontent.com/anttiharju/check-relative-markdown-links/$sha/install.sh" | sh
    - name: Check relative markdown links
      working-directory: ${{ inputs.working-directory }}
      shell: sh
      run: check-relative-markdown-links run
