name: check-relative-markdown-links
description: Runs check-relative-markdown-links on default settings
inputs:
  sha:
    required: false
    description: "SHA of the commit from which to install the tool"
    default: 00d570b049a30799afa76e319deaec65542f735b

runs:
  using: "composite"
  steps:
    - name: Check relative markdown links
      shell: sh
      env:
        sha: ${{ inputs.sha }}
      run: |
        curl -sSfL "https://raw.githubusercontent.com/anttiharju/check-relative-markdown-links/$sha/check-relative-markdown-links.bash" | bash -s -- run --verbose --color=always
