name: check-relative-markdown-links
description: Runs check-relative-markdown-links on default settings
inputs:
  sha:
    required: false
    description: "SHA of the commit from which to install the tool"
    default: fc5154ae49be72ad3aee8d42c64ab894c76d8d92

runs:
  using: "composite"
  steps:
    - name: Check relative markdown links
      shell: sh
      env:
        sha: ${{ inputs.sha }}
      run: |
        curl -sSfL "https://raw.githubusercontent.com/anttiharju/check-relative-markdown-links/$sha/check-relative-markdown-links.bash" | bash -s -- run --verbose
