name: relcheck
description: Runs relcheck on default settings
inputs:
  version:
    description: relcheck version to install
    required: false
    default: 1.0.0

runs:
  using: "composite"
  steps:
    - name: Cache
      id: cache
      uses: actions/cache@v4
      with:
        path: /usr/local/bin/relcheck
        key: relcheck-${{ inputs.version }}-linux
    - if: steps.cache.outputs.cache-hit != 'true'
      name: Install
      working-directory: /usr/local/bin
      shell: sh
      env:
        url: https://github.com/anttiharju/relcheck/releases/download/v${{ inputs.version }}/relcheck-linux-amd64.tar.gz
        tmp: ${{ runner.temp }}
      run: |
        curl -sSL "$url" | tar -xz --strip-components=0 relcheck
    - name: Run relcheck
      shell: sh
      run: |
        relcheck all --verbose --color=always
