name: relcheck
description: Downloads, caches, and runs relcheck with verbose output on files tracked by Git.
inputs:
  version:
    description: relcheck version in semver format without the 'v' prefix
    required: false
    default: "1.8.8"
  install-path:
    description: Installation path without trailing slash for the binary
    required: false
    default: /usr/local/bin
runs:
  using: "composite"
  steps:
    - name: relcheck
      uses: anttiharju/relcheck@v1.8.8
      with:
        version: ${{ inputs.version }}
        install-path: ${{ inputs.install-path }}
