name: "Filter Changes"
description: "Filter changed files based on glob patterns extracted from a YAML file"
inputs:
  changes:
    description: "JSON array of changed files"
    required: true
  file:
    description: "YAML file to extract glob pattern from"
    required: true
  yq:
    description: "yq expression to extract glob pattern from the YAML file"
    required: true
runs:
  using: "composite"
  steps:
    - name: Filter changes
      id: changed
      shell: sh
      env:
        changes: ${{ inputs.changes }}
        yq: ${{ inputs.yq }}
        file: ${{ inputs.file }}
        expression: ${{ runner.temp }}/expression
      run: |
        "$GITHUB_ACTION_PATH/action.py"
outputs:
  have_changed:
    description: "Boolean indicating whether any of the changed files match the glob pattern"
    value: ${{ steps.filter.outputs.have_changed }}
