name: ShellCheck
description: Runs ShellCheck with colorful output

runs:
  using: "composite"
  steps:
    - shell: sh
      run: |
        shellcheck --color=always --source-path=SCRIPTDIR $(git ls-files '*.sh' '*.bash')
