name: ShellCheck
description: Runs ShellCheck with colorful output
inputs:
  version:
    description: ShellCheck version to install
    required: false
    default: v0.10.0

runs:
  using: "composite"
  steps:
    - name: Cache ShellCheck binary
      id: cache
      uses: actions/cache@v4
      with:
        path: /usr/local/bin/shellcheck
        key: shellcheck-${{ inputs.url }}
    - if: steps.cache.outputs.cache-hit == 'false'
      name: Install
      shell: sh
      env:
        URL: https://github.com/koalaman/shellcheck/releases/download/${{ inputs.version }}/shellcheck-${{ inputs.version }}.linux.x86_64.tar.xz
        TMP: ${{ runner.temp }}
      run: |
        "$GITHUB_ACTION_PATH/install.sh"
    - shell: sh
      run: |
        "$GITHUB_ACTION_PATH/run.sh"
