name: Rubocop file
description: Run Rubocop on a specific file.
inputs:
  file:
    description: "The file to run Rubocop on."
    required: true
    default: .
  ruby-version:
    description: The version of Ruby to use.
    required: false
    default: 3.4.4
  version:
    description: The version of rubocop to install.
    required: false
    default: 1.75.8
runs:
  using: "composite"
  steps:
    - name: Create Gemfile
      shell: sh
      env:
        version: ${{ inputs.version }}
      run: |
        {
          echo '# frozen_string_literal: true'
          echo ''
          echo "source 'https://rubygems.org'"
          echo ''
          echo "gem 'rubocop', '$version'"
        } > Gemfile
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ inputs.ruby-version }}
        bundler-cache: true
    - shell: sh
      env:
        file: ${{ inputs.file }}
      run: bundle exec rubocop "$file"
