name: Ban .yaml
description: Enforce file extension consistency by mandating .yml

runs:
  using: "composite"
  steps:
    - name: Check for .yaml files
      shell: sh
      run: |
        YAML_FILES=$(git ls-files '*.yaml')
        if [ -n "$YAML_FILES" ]; then
          echo "Found the following .yaml files. Please use .yml extension instead."
          echo "$YAML_FILES"
          exit 1
        fi
        echo "No .yaml files found. Good job!"
