name: Update docs
description: Updates docs/ directory to gh-pages branch.
inputs:
  committer:
    description: 'Committer username'
    required: false
    default: "github-actions[bot]"

runs:
  using: "composite"
  steps:
    - shell: sh
      env:
        GIT_AUTHOR_NAME: ${{ github.actor }}
        GIT_AUTHOR_EMAIL: "${{ github.actor }}@users.noreply.github.com"
        GIT_COMMITTER_NAME: "${{ inputs.committer }}"
        GIT_COMMITTER_EMAIL: "${{ inputs.committer }}@users.noreply.github.com" 
      run: |
        pip install mkdocs
        mkdocs gh-deploy --force --no-history
