name: "Check Changes"
description: "Check changed files based on glob patterns extracted from a YAML file"
inputs:
  changes:
    description: "JSON array of changed files"
    required: true
  file:
    description: "YAML file to extract glob pattern from"
    required: true
  yq:
    description: "yq expression to extract glob pattern from the YAML file"
    required: true
  force-true:
    description: "Whether to force the output to be true"
    required: false
    default: "false"
runs:
  using: "composite"
  steps:
    - name: Check changes
      id: state
      shell: sh
      env:
        changes: ${{ inputs.changes }}
        yq: ${{ inputs.yq }}
        file: ${{ inputs.file }}
        expression_path: ${{ runner.temp }}/expression
        force_true: ${{ inputs.force-true }}
      run: |
        # Run check-changes
        if [ "$force_true" = "true" ]; then
          echo "force-true input is set to true (default false), forcing changes output to true"
          echo "changes=true"
          echo "changes=true" >> "$GITHUB_OUTPUT"
          exit 0
        else
          "$GITHUB_ACTION_PATH/action.py"
        fi
outputs:
  changed:
    description: "Boolean indicating whether any of the changed files match the glob pattern"
    value: ${{ steps.state.outputs.changed }}
