name: go build
description: Build a binary with go

runs:
  using: "composite"
  steps:
    - name: Cache Go
      uses: actions/cache@v4
      with:
        path: /opt/hostedtoolcache/go
        key: ${{ runner.os }}-${{ runner.arch }}-go-${{ hashFiles('go.mod') }}
    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version-file: "go.mod"
        cache: false
    - shell: sh
      run: go build
