name: go build
description: Build a binary with go

runs:
  using: "composite"
  steps:
    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version-file: "go.mod"
    - shell: sh
      run: go build
