name: Release
description: "Create a release"

runs:
  using: "composite"
  steps:
    - name: Calculate title (build number)
      id: titler
      shell: sh
      run: |
        latest_release_title=$(gh release view --json name -q '.name' || echo 'Build 0')
        latest_release_number=${latest_release_title#"Build "}
        this_release_number=$((latest_release_number + 1))
        this_release_title="Build $this_release_number"
        echo "title=$this_release_title" >> "$GITHUB_OUTPUT"
        echo "number=$this_release_number" >> "$GITHUB_OUTPUT"
    - name: Tag current commit
      id: tagger
      shell: sh
      env:
        NUMBER: ${{ steps.titler.outputs.number }}
      run: |
        TAG="build$NUMBER"
        git tag "$TAG"
        git push origin "$TAG"
        echo "tag=$TAG" >> "$GITHUB_OUTPUT"
    - name: Create a release
      shell: sh
      env:
        TITLE: ${{ steps.titler.outputs.title }}
        TAG: ${{ steps.tagger.outputs.tag }}
        GH_TOKEN: ${{ github.token }}
      run: |
        gh release create "$TAG" --title="$TITLE" --generate-notes
