name: Release
description: "Creates a release"
inputs:
  type:
    description: "major, minor, or patch"
    required: true
runs:
  using: "composite"
  steps:
    - name: Get latest release title
      id: latest
      shell: sh
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        version=$(gh release view --json name -q '.name' || echo '0.0.0')
        {
          major="$(echo "$version" | cut -d. -f1)"
          minor="$(echo "$version" | cut -d. -f2)"
          patch="$(echo "$version" | cut -d. -f3)"
        } >> "$GITHUB_OUTPUT"
    - if: ${{ inputs.type == 'major' }}
      name: Bump major version
      id: this
      shell: bash
      env:
        type: ${{ inputs.type }}
        major: ${{ steps.latest.outputs.major }}
        minor: ${{ steps.latest.outputs.minor }}
        patch: ${{ steps.latest.outputs.patch }}
      run: |
        if [ "$type" = "major" ]; then
          echo "version=$((major + 1)).0.0" >> "$GITHUB_OUTPUT"
        fi
        if [ "$type" = "minor" ]; then
          echo "version=$major.$((minor + 1)).0" >> "$GITHUB_OUTPUT"
        fi
        if [ "$type" = "patch" ]; then
          echo "version=$major.$minor.$((patch + 1))" >> "$GITHUB_OUTPUT"
        fi
    - name: Tag current commit
      id: tagger
      shell: sh
      env:
        semver: ${{ steps.this.outputs.version }}
      run: |
        tag="v$semver"
        git tag "$tag"
        git push origin "$tag"
        echo "tag=$tag" >> "$GITHUB_OUTPUT"
    - name: Create a release
      shell: sh
      env:
        GH_TOKEN: ${{ github.token }}
        TAG: ${{ steps.tagger.outputs.tag }}
        TITLE: ${{ steps.this.outputs.version }}
      run: |
        gh release create "$TAG" --title="$TITLE" --generate-notes
outputs:
  tag:
    description: "The tag created"
    value: ${{ steps.tagger.outputs.tag }}
