name: Release
description: "Creates a release"
inputs:
  version:
    description: "Version for the new release"
    required: true
runs:
  using: "composite"
  steps:
    - name: Tag current commit
      shell: sh
      env:
        tag: "v${{ inputs.version }}"
      run: |
        git tag "$tag"
        git push origin "$tag"
    - name: Create a release
      shell: sh
      env:
        GH_TOKEN: ${{ github.token }}
        TITLE: ${{ inputs.version }}
        tag: "v${{ inputs.version }}"
      run: |
        gh release create "$tag" --title="$TITLE" --generate-notes
outputs:
  tag:
    description: "The tag created"
    value: "v${{ inputs.tag }}"
