name: Release
description: "Creates a release"
inputs:
  title:
    description: "Release title"
    required: true
  tag:
    description: "Release tag"
    required: false
runs:
  using: "composite"
  steps:
    - name: Tag current commit
      shell: sh
      env:
        tag: "${{ inputs.tag }}"
      run: |
        git tag "$tag"
        git push origin "$tag"
    - name: Create a release
      shell: sh
      env:
        GH_TOKEN: ${{ github.token }}
        title: ${{ inputs.title }}
        tag: "${{ inputs.tag }}"
      run: |
        gh release create "$tag" --title="$title" --generate-notes
