name: Find changes

description: Find changes within the first-level directories of the repo and output them for matrix strategy.

inputs:
  github-token:
    description: 'GitHub token'
    required: true

# DO THIS:
#
# checkout
#     default branch
#     pull request branch
#
# on pull_request easy to diff, requires only 2 checkout with depth 1
# on push find the associated PR, and do the diff the same way as on pull_request -- no surprises on push!
# 
# on any API call do graceful backoff (3 times, 1. immediately, 2. after 1s, 3. after 5s)
#         github actions telemetry (baked into a monorepo to be used within an org) and visualised on grafana etc would be really cool + use case for playing with dedicated servers.

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
    - name: Get default branch name # extract this into a separate action
      shell: bash
      run: |
        DEFAULT_BRANCH=$(curl -s -H "Authorization: token ${{ inputs.github-token }}" \
          https://api.github.com/repos/${{ github.repository }} | jq -r .default_branch)
        echo "DEFAULT_BRANCH=$DEFAULT_BRANCH" >> $GITHUB_ENV
    - name: Find changes
      id: find_changes
      shell: bash
      run: $GITHUB_ACTION_PATH/script.sh $DEFAULT_BRANCH

outputs:
  directories:
    description: 'JSON array of changed first-level directories'
    value: ${{ steps.find_changes.outputs.directories }}
