name: "Sync default.nix"
description: "Ensure that the list of packages in default.nix is up to date"
inputs:
  working-directory:
    description: "The working directory where default.nix is located"
    required: false
    default: "${{ github.workspace }}"
runs:
  using: "composite"
  steps:
    - name: Update default.nix
      working-directory: ${{ inputs.working-directory }}
      shell: sh
      run: |
        "$GITHUB_ACTION_PATH/action.bash"
