name: Require Semver Label
description: "Ensures PR has exactly one semver label (major, minor, or patch)"
inputs:
  error-message:
    description: "Message to echo upon failure"
    required: false
    default: "PR must have exactly one of the following labels: major, minor, patch"
runs:
  using: "composite"
  steps:
    - name: Get labels
      id: label
      uses: anttiharju/actions/get-labels@v0

    - name: Check for major label
      id: major
      uses: anttiharju/actions/require-label@v0
      with:
        labels: ${{ steps.label.outputs.names }}
        name: "major"
        error-message: ${{ inputs.error-message }}

    - name: Check for minor label
      id: minor
      uses: anttiharju/actions/require-label@v0
      with:
        labels: ${{ steps.label.outputs.names }}
        name: "minor"
        error-message: ${{ inputs.error-message }}
        fail-on-match: ${{ steps.major.outputs.match }}

    - name: Check for patch label
      id: patch
      uses: anttiharju/actions/require-label@v0
      with:
        labels: ${{ steps.label.outputs.names }}
        name: "patch"
        error-message: ${{ inputs.error-message }}
        fail-on-match: ${{ steps.minor.outputs.match == 'true' || steps.major.outputs.match == 'true' }}

    - if: ${{ steps.major.outputs.match == 'false' && steps.minor.outputs.match == 'false' && steps.patch.outputs.match == 'false' }}
      name: Fail if no semver label matched
      shell: sh
      env:
        ERROR_MESSAGE: ${{ inputs.error-message }}
      run: |
        echo "Error: $ERROR_MESSAGE"
        exit 1
outputs:
  bump:
    description: "The type of semver bump to be applied"
    value: ${{ steps.major.outputs.match == 'true' && 'major' || steps.minor.outputs.match == 'true' && 'minor' || steps.patch.outputs.match == 'true' && 'patch' || 'no-release' }}
