name: Hash Nix
description: Calculates a hash required for packaging software via Nix flakes
inputs:
  rev:
    description: The git revision (commit SHA) to hash
    required: false
    default: ${{ github.sha }}
runs:
  using: "composite"
  steps:
    - uses: cachix/install-nix-action@fd24c48048070c1be9acd18c9d369a83f0fe94d7 # v31
      with:
        nix_path: nixpkgs=channel:nixos-25.05
    - name: Hash Nix
      shell: sh
      env:
        owner: ${{ github.repository_owner }}
        repository: ${{ github.event.repository.name }}
        rev: ${{ inputs.rev }}
      run: |
        sha256="$(nix-prefetch-url --quiet --unpack "https://github.com/$owner/$repository/archive/$rev.tar.gz")"
        echo "sha256=$sha256" >> "$GITHUB_OUTPUT"
        echo "$sha256"
        hash="$(nix hash convert --hash-algo sha256 --to sri "$sha256")"
        echo "hash=$hash" >> "$GITHUB_OUTPUT"
        echo "$hash"
outputs:
  sha256:
    description: The SHA256 hash for the current commit
    value: ${{ steps.nix.outputs.sha256 }}
  hash:
    description: The calculated hash for the current commit
    value: ${{ steps.nix.outputs.hash }}
