name: Hash Nix
description: Calculates a hash required for packaging software via Nix flakes
inputs:
  version:
    description: The version of nix-prefetch-github to install.
    required: false
    default: "7.1.0"
runs:
  using: "composite"
  steps:
    - uses: cachix/install-nix-action@fd24c48048070c1be9acd18c9d369a83f0fe94d7 # v31
      with:
        nix_path: nixpkgs=channel:nixos-25.05
    - name: Hash Nix
      shell: sh
      env:
        version: ${{ inputs.version }}
        owner: ${{ github.repository_owner }}
        repository: ${{ github.event.repository.name }}
        rev: ${{ github.sha }}
      run: |
        echo "hash=$(nix hash convert --hash-algo sha256 --to sri "$(nix-prefetch-url --quiet --unpack "https://github.com/$owner/$repository/archive/$rev.tar.gz")")" >> "$GITHUB_OUTPUT"
        echo "$hash"
outputs:
  hash:
    description: The calculated hash for the current commit
    value: ${{ steps.nix.outputs.hash }}
