name: action-validator
description: Runs action-validator on files tracked by Git.
inputs:
  version:
    description: action-validator version to install
    required: false
    default: 0.6.0

runs:
  using: "composite"
  steps:
    - name: Cache
      id: cache
      uses: actions/cache@v4
      with:
        path: /usr/local/bin/action-validator
        key: action-validator-${{ inputs.version }}
    - if: steps.cache.outputs.cache-hit != 'true'
      name: Install
      shell: sh
      env:
        URL: https://github.com/mpalmer/action-validator/releases/download/v${{ inputs.version }}/action-validator_linux_amd64
        TMP: ${{ runner.temp }}
      run: |
        curl -sSL "$URL" -o "$TMP"
        ls "$TMP"
        cp "$TMP/action-validator" /usr/local/bin
    - name: Run
      shell: sh
      run: |
        action-validator --verbose $(git ls-files ".github/*/*.yml" "*/action.yml")
