name: action-validator
description: Discover files for action-validator and execute it on them

runs:
  using: "composite"
  steps:
    - name: Download action-validator
      uses: asdf-vm/actions/install@05e0d2ed97b598bfce82fd30daf324ae0c4570e6
      with:
        tool_versions: action-validator 0.6.0
    - name: Run action-validator
      shell: sh
      run: |
        find ./.github -mindepth 2 -type f -name "*.yml" -exec action-validator --verbose {} +
