name: actionlint
description: Downloads, caches, and runs actionlint with verbose output on files tracked by Git.
inputs:
  version:
    description: actionlint version in semver format without the 'v' prefix
    required: false
    default: "latest"
branding:
  icon: check
  color: green
runs:
  using: "composite"
  steps:
    - name: Debug
      shell: bash
      run: |
        echo "Runner OS: ${{ runner.os }}"
        echo "Runner Arch: ${{ runner.arch }}"
        echo "PATH: $PATH"
    - name: Resolve version
      id: resolve
      shell: bash
      env:
        GH_TOKEN: ${{ github.token }}
        version: ${{ inputs.version }}
      run: |
        if [[ "$version" = "latest" ]]; then
          tag="$(gh release view --repo rhysd/actionlint --json tagName -q .tagName)"
          version="${tag#v}"
        fi
        echo "version=$version" >> "$GITHUB_OUTPUT"
    - name: Convert target
      id: convert
      shell: sh
      env:
        os: ${{ runner.os }} # Possible values are Linux, Windows, or macOS.
        arch: ${{ runner.arch }} # Possible values are X86, X64, ARM, or ARM64.
        version: ${{ steps.resolve.outputs.version }}
      run: |
        target="$os-$arch"
        case "$target" in
          macOS-ARM64)
            echo "target=${version}_darwin_arm64" >> "$GITHUB_OUTPUT"
            echo "ext=tar.gz" >> "$GITHUB_OUTPUT"
            echo "install_path=/usr/bin" >> "$GITHUB_OUTPUT"
            ;;
          macOS-X64)
            echo "target=${version}_darwin_amd64" >> "$GITHUB_OUTPUT"
            echo "ext=tar.gz" >> "$GITHUB_OUTPUT"
            echo "install_path=/usr/bin" >> "$GITHUB_OUTPUT"
            ;;
          Linux-ARM64)
            echo "target=${version}_linux_arm64" >> "$GITHUB_OUTPUT"
            echo "ext=tar.gz" >> "$GITHUB_OUTPUT"
            echo "install_path=/usr/bin" >> "$GITHUB_OUTPUT"
            ;;
          Linux-X64)
            echo "target=${version}_linux_amd64" >> "$GITHUB_OUTPUT"
            echo "ext=tar.gz" >> "$GITHUB_OUTPUT"
            echo "install_path=/usr/bin" >> "$GITHUB_OUTPUT"
            ;;
          Windows-X86)
            echo "target=${version}_windows_386" >> "$GITHUB_OUTPUT"
            echo "ext=zip" >> "$GITHUB_OUTPUT"
            echo "install_path=C:/Program Files/Git/usr/bin" >> "$GITHUB_OUTPUT"
            ;;
          Windows-X64)
            echo "target=${version}_windows_386" >> "$GITHUB_OUTPUT"
            echo "ext=zip" >> "$GITHUB_OUTPUT"
            echo "install_path=C:/Program Files/Git/usr/bin" >> "$GITHUB_OUTPUT"
            ;;
          -X86)
            echo "target=${version}_windows_386" >> "$GITHUB_OUTPUT"
            echo "ext=zip" >> "$GITHUB_OUTPUT"
            echo "install_path=C:/Program Files/Git/usr/bin" >> "$GITHUB_OUTPUT"
            ;;
          -X64)
            echo "target=${version}_windows_386" >> "$GITHUB_OUTPUT"
            echo "ext=zip" >> "$GITHUB_OUTPUT"
            echo "install_path=C:/Program Files/Git/usr/bin" >> "$GITHUB_OUTPUT"
            ;;
          *)
            echo "Unsupported os-arch target: $target" >&2; exit 1
            ;;
        esac
    - name: Cache
      id: cache
      uses: actions/cache@v4
      with:
        path: ${{ steps.convert.outputs.install_path }}/actionlint
        key: actionlint_v${{ steps.convert.outputs.target }}
    - if: steps.cache.outputs.cache-hit != 'true'
      name: Install
      working-directory: ${{ runner.temp }}
      shell: sh
      env:
        GH_TOKEN: ${{ github.token }}
        version: ${{ steps.resolve.outputs.version }}
        target: ${{ steps.convert.outputs.target }}
        ext: ${{ steps.convert.outputs.ext }}
        install_path: ${{ steps.convert.outputs.install_path }}
      run: |
        printf 'gh release download "v%s" --repo rhysd/actionlint --pattern "actionlint_%s.%s"\n' "$version" "$target" "$ext"
        gh release download "v$version" --repo rhysd/actionlint --pattern "actionlint_$target.$ext"
        case "$ext" in
          zip)
            unzip -j "actionlint_$target.$ext" actionlint.exe
            mv actionlint.exe "$install_path/actionlint"
            ;;
          tar.gz)
            tar -xzf "actionlint_$target.$ext" actionlint
            mv actionlint "$install_path"
            ;;
          *)
            echo "Unknown archive format: $ext" >&2
            exit 1
            ;;
        esac
    - name: Run
      shell: sh
      run: |
        actionlint -color
