on:
  pull_request:
  push:
    branches:
      - v0

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # note: only lints under .github/
      # I don't think these tools are capable
      # of linting composite actions well
      - name: Actions
        uses: ./lint-actions

      - if: always()
        name: Prettier
        uses: ./check-prettier

      - if: always()
        name: EditorConfig
        uses: anttiharju/actions/check-editorconfig@v0
