on:
  pull_request:
  push:
    branches:
      - v0

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Actions
        uses: ./lint-actions

      - if: always()
        name: ShellCheck
        uses: ./run-shellcheck

      - if: always()
        name: Markdown
        uses: ./run-markdown-link-check

      - if: always()
        name: Prettier
        uses: ./run-prettier

      - if: always()
        name: EditorConfig
        uses: ./run-editorconfig-checker
