on:
  pull_request:
  push:
    branches:
      - v0

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: action-validator
        uses: ./action-validator

      - if: always()
        name: actionlint
        uses: ./actionlint

      - if: always()
        name: relcheck
        uses: ./relcheck

      - if: always()
        name: Prettier
        uses: ./prettier

      - if: always()
        name: EditorConfig-Checker
        uses: ./editorconfig-checker
