name: check-lefthook-glob
on:
  pull_request:
    paths:
      - ".github/workflows/check-lefthook-glob.yml"
      - "check-lefthook-glob/**/*"
      - "find-changes/**/*"
      - "!find-changes/README.md"
  push:
    branches:
      - v0
    paths:
      - ".github/workflows/check-lefthook-glob.yml"
      - "check-lefthook-glob/**/*"
      - "find-changes/**/*"
      - "!find-changes/README.md"

jobs:
  example:
    name: Example
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Find changes
        id: changes
        uses: ./find-changes

      - name: Check Lefthook glob
        id: workflows
        uses: ./check-lefthook-glob
        with:
          changes: ${{ steps.changes.outputs.array }}
          yq: '.pre-commit.jobs[] | select(.name == "actionlint") | .glob'

      - if: steps.workflows.outputs.changed == 'true'
        name: Echo true
        shell: sh
        run: |
          echo ${{ steps.workflows.outputs.changed }}
