name: check-shellcheck
on:
  pull_request:
    paths:
      - ".github/workflows/check-shellcheck.yml"
      - "check-shellcheck/**/*"
      - "!check-shellcheck/README.md"
  push:
    branches:
      - v0
    paths:
      - ".github/workflows/check-shellcheck.yml"
      - "check-shellcheck/**/*"
      - "!check-shellcheck/README.md"

jobs:
  test:
    name: Test
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Test
        working-directory: check-shellcheck
        shell: sh
        run: ./test.py
