name: find-changes
on:
  pull_request:
    paths:
      - ".github/workflows/find-changes.yml"
      - "find-changes/**/*"
      - "!find-changes/README.md"
  push:
    branches:
      - v0
    paths:
      - ".github/workflows/find-changes.yml"
      - "find-changes/**/*"
      - "!find-changes/README.md"

jobs:
  test:
    name: Test
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Find changes
        id: changed
        uses: anttiharju/actions/find-changes@77ee8c08cd2350d5935d1b5dd2575c535456dc64

      - name: Echo changed files
        shell: sh
        run: |
          echo ${{ steps.changed.outputs.files }}
