on:
  pull_request:
  push:
    branches:
      - main

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prettier
        uses: ./run-prettier
