name: relcheck
permissions:
  contents: read
  pull-requests: read

on:
  pull_request:
    paths:
      - 'relcheck/**'
  push:
    branches:
      - v0
    paths:
      - 'relcheck/**'

jobs:
  run:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: relcheck
        uses: ./relcheck
