name: render-template
on:
  pull_request:
    paths:
      - ".github/workflows/render-template.yml"
      - "render-template/**/*"
      - "!render-template/README.md"
  push:
    branches:
      - v0
    paths:
      - ".github/workflows/render-template.yml"
      - "render-template/**/*"
      - "!render-template/README.md"

jobs:
  test:
    name: Test
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Render template
        uses: ./render-template
        with:
          working-directory: render-template/testdata
          template: template
          values: values
          output: got

      - name: Test
        working-directory: render-template/testdata
        run: diff got want

      - name: Print output
        working-directory: render-template/testdata
        run: cat got
