name: Release docs
description: Releases project documentation to GitHub Pages.
inputs:
  committer:
    description: 'Committer username'
    required: false
    default: "github-actions[bot]"

runs:
  using: "composite"
  steps:
    - shell: sh
      env:
        GIT_COMMITTER_NAME: "${{ inputs.committer }}"
        GIT_COMMITTER_EMAIL: "${{ inputs.committer }}@users.noreply.github.com" 
      run: |
        pip install mkdocs
        mkdocs gh-deploy --force --no-history
